### ISSUE TITLE
after search then action onPress

### ISSUE THREAD

**Issue by agungs17** [fattahmuhyiddeen/react-native-complete-flatlist#11]
after search the onPress
result like this : 
$$typeof: Symbol(react.element)
key: null
props: {highlightStyle: {…}, searchWords: Array(1), textToHighlight: "13161"}
ref: null
type: ƒ Highlighter(_ref)
_owner: FiberNode {tag: 1, key: null, stateNode: CompleteFlatList, elementType: ƒ, type: ƒ, …}
_store: {validated: false}

**Comment by fattahmuhyiddeen** [comment]
can you share your code?

**Comment by fattahmuhyiddeen** [comment]
@agungs17 

maybe this note will help you (from README.md)


renderItem props return data and index parameters data parameter returns a single element in data array. But if search text is not empty, data parameter will return new structure of JSON object (in order to render highlighted text in jsx). This might break your logic. Therefore, if you want to access original structure of your data, it will be under data.cleanData. Remember, data.cleanData only exist if search text is not empty (user is searching)

**Comment by fattahmuhyiddeen** [comment]
@agungs17 I already update the sample code to remove the highlightColor props. if you want to use that props, you have to read the precaution. use the clearData to access original structure of your data
