### ISSUE TITLE
slide animation

### ISSUE THREAD

**Issue by jonassahin01** [fattahmuhyiddeen/react-native-complete-flatlist#12]
hey, awesome work on this component!

for some reason, the slide animation is broken or it's my bad code. 

at initial launch, the slide animation works totally fine but after you search & remove lettering it makes the view empty thus it's unable to rerender the flat list items, the Flatlist item view element is still there but no styling on that element, do you know what could cause such thing?

**Comment by fattahmuhyiddeen** [comment]
thanks @Jonas-rbg 
there are 2 solutions.

1. you remove `highlightColor` props. this will disable text highlighting

or

2. inside renderItem, for example you have `title`, you have to access like this example.
```js
renderItem={({data}) => {
  const title = data.cleanData?.title || data.title;
  return (<Text>{title}</Text>)
}}
```
this is because, after search, to enable the text highlighting, the structure of the original data is changed. therefore you have to use `cleanData` to get your original code
